spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security #?connectionTimeZone=UTC #change this to your database url
    password:  password #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone: UTC #To fix wampp server error on Africa's time Zone
      ddl-auto: update